pastagang/nudel

- package-lock.json
I got an error when doing `pnpm i` so i just did `npm i` and that worked too. can a repo just have both? is that allowed?
> Add npm support too

- package-lock.json
- src/style.css
https://github.com/user-attachments/assets/d997663d-0eb9-4d2f-a1ca-4dd8e64c4ab5
> Switch to one column on mobile

- index.html
- src/style.css
Trying to make things a bit clearer
- buttons (ie: switch elements) more clearly buttons.
- more clear divisions between panes.
- more hierarchy of the pane "heading"
- remove line numbers which can be overwhelming. could add setting to reshow them.
> Increase brutalism

- index.html
- src/main.js
- src/style.css
adds a run button. good for mobile users, and also good for discovery on laptop/desktop
> Add run button

- src/theme.js
```
// sorry froos I'm turning this off because it's a power user feature
// Let's add settings for this!!!!!!!!!!
```
> Switch back to thin caret

- src/main.js
Lets add a setting for it!
This makes it more usable on phones though
> Disable line wrapping

- index.html
- src/style.css
making some room for things like settings and discovery, and i think its less scary/confusing for newbies.
i think this is maybe preferable to a splash screen
> add a big title

- index.html
- src/style.css
hot take, I dont think the mantra should be changed from within the app. i think we could keep it as a good "low hanging fruit" to get people's foot in the door for contributing to this repo
could even have a button/link that takes people to the right file to edit
> Add a mantra

- src/shader.js
> Keep the shader running when iTime is used

- index.html
- package-lock.json
- src/settings.js
Changes:
- index.html: Added username input field to about-dialog form
- settings.js: Added event listeners and handlers for welcome dialog username sync
- Added welcomeUsernameInput handling in settings.js to maintain state between both dialogs
> added username field to welcome dialog, sync username 

- index.html
- src/settings.js
- src/style.css
> Add export button

- index.html
- src/settings.js
- src/style.css
moved top 3 buttons and mcplant to a burger menu
> Added a burger menu (Issue #55)

- src/settings.js
> prevent default for dropdown

- src/error.js
- src/main.js
- src/shader.js
- src/style.css
implements inline errors for shaders only as discussed in #63
> inline errors for shaders

- src/editor.js
- src/main.js
might not actually work.. go poop urself https://vm.tiktok.com/ZGdDejPrx/
> Outlaw undo / redo

- index.html
- panels/strudel.html
- src/editor.js
- src/main.js
- src/settings.js
- src/strudel.js
- src/style.css
- new settings page design
- disable strudel highlighting
- cleaned up settings innards
> Add performance section to settings and add option to disable highlights

- index.html
- script.js
- src/declare.d.ts
- src/error.js
- src/export.js
- src/main.js
- src/random.js
- src/session.js
- src/settings.js
- src/strudel.js
- src/style.css
- src/url.js
AND MANY OTHER THINGS
`nudel.cc?room=foo` also works
`nudel.cc?room` to reset to pasta room
> Add setting to change room

- src/editor.js
> Make chat messages be colored the same as the pointer

- src/strudel-cyclist.js
- src/strudel.js
this is LIVE coding not DEAD coding
will merge and carry on on main
> why am i doing this on a branch

- src/mantra.js
- src/random.js
> Conditional mantras

- src/main.js
- src/random.js
using techniques similar to those used in authenticator apps, mantras will now appear in random order
> Proper random mantras

- panels/hydra.html
My first PR on nudel 🍝 🤩
I just really want to use p5.
I tested it locally with `npm run dev` and was able to draw a rectangle! 
Totally copied from [hydra source](https://github.com/hydra-synth/hydra/blob/3668d10bfdcff813dd4adc9b29b0e4e6287393bc/src/lib/p5-wrapper.js#L5).
Beautiful things are going to come! If I hopefully don't break it all 😱
> Working p5 ✨

- src/session.js
Y.js data model accretes over time, new room starts from small again. 
https://www.pastagang.cc/blog/performance/
> Another month, another room. We're in pastagang6 now.
